In [1]:
print("hello world")

hello world


In [2]:
import numpy as np 

In [60]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [4]:
arr = np.array([10,20,30,40,50])   # to create an array 
arr 

array([10, 20, 30, 40, 50])

In [5]:
print(type(arr))

<class 'numpy.ndarray'>


In [6]:
arr.dtype

dtype('int64')

In [7]:
arr = np.array([10,20,30,40,50,20.2])   # to create an array 
arr 

array([10. , 20. , 30. , 40. , 50. , 20.2])

In [8]:
arr = np.array([10,20,30,40,50,"Upflairs"])   # to create an array 
arr 

array(['10', '20', '30', '40', '50', 'Upflairs'], dtype='<U21')

In [9]:
arr.ndim    # dimension of array 

1

In [10]:
arr = np.array([[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]])   # [ [1d] , [1d] , [1D] , [1D]  ]
arr 

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [11]:
ls = [[[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]],
       [[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]]]

# print(ls)
# print(type(ls))
arr = np.array(ls)
arr 

array([[[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]],

       [[10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50],
        [10, 20, 30, 40, 50]]])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.ndim 

3

In [14]:
arr = np.array([10,20,30,40,50])   # to create an array 
arr 

array([10, 20, 30, 40, 50])

In [15]:
arr[-2]  # single item 

np.int64(40)

In [16]:
arr[::3]

array([10, 40])

In [17]:
arr[::1]

array([10, 20, 30, 40, 50])

In [18]:
arr[::-1]


array([50, 40, 30, 20, 10])

In [19]:
arr 

array([10, 20, 30, 40, 50])

In [20]:
arr = np.array([[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50],[10,20,30,40,50]])   # [ [1d] , [1d] , [1D] , [1D]  ]
arr 

array([[10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50],
       [10, 20, 30, 40, 50]])

In [21]:
arr = np.random.randint(1,50,(3,5,4))  #  
arr 

array([[[22, 16, 45, 34],
        [34, 27, 16, 20],
        [46, 20, 40, 32],
        [47, 36, 30, 28],
        [37, 33, 11, 31]],

       [[24, 26, 18, 29],
        [36, 44, 21, 45],
        [21,  5, 33, 17],
        [24, 27, 31, 27],
        [ 8,  7, 48, 33]],

       [[26, 14, 22, 13],
        [34, 38,  7,  4],
        [37,  1, 26, 29],
        [16, 35, 27, 22],
        [30, 23, 28,  5]]], dtype=int32)

In [22]:
arr = np.random.randint(1,50,10)  # 1D array creating with randomly 
arr 

array([39, 26, 17, 48,  4, 40, 10,  1, 47,  2], dtype=int32)

In [23]:
arr = np.random.randint(1,50,(5,8))  # 2D array creating with randomly 
arr 

array([[20, 19, 46, 30, 48,  4, 48, 42],
       [34, 20, 47, 32, 41, 45,  5, 29],
       [ 2,  2,  3, 26,  6,  4, 43, 41],
       [40, 35, 10, 11,  4, 39, 41, 16],
       [35,  8, 23, 22, 41, 32, 10, 26]], dtype=int32)

In [24]:
arr.shape  

(5, 8)

In [25]:
arr = np.random.randint(1,50,(3,4,3))  # 3D array creating with randomly 
arr 

array([[[15, 18, 12],
        [35, 15, 11],
        [39, 43, 21],
        [44, 40, 34]],

       [[ 9, 41, 27],
        [18, 46, 40],
        [40, 42, 45],
        [ 2, 31, 21]],

       [[23, 31, 15],
        [ 5, 31,  4],
        [37, 45, 41],
        [27,  1, 33]]], dtype=int32)

In [26]:
arr = np.random.random(10)
arr 
# random  in btwn 0 - 1 , randomly initialize 

array([0.29634197, 0.99526769, 0.59039744, 0.33089409, 0.75530587,
       0.24256547, 0.30343206, 0.23956064, 0.96338615, 0.63251427])

In [27]:
arr = np.random.random((5,4))
arr 

array([[0.44860472, 0.36004494, 0.25842337, 0.48621983],
       [0.39302946, 0.7803154 , 0.54782838, 0.28435805],
       [0.39004519, 0.31506042, 0.59318559, 0.92244153],
       [0.29191921, 0.95135335, 0.38044285, 0.80369192],
       [0.86469208, 0.82142235, 0.22438595, 0.66087268]])

In [28]:
arr = np.random.random((2,5,4))
arr 

array([[[0.01638149, 0.22926517, 0.08596594, 0.94750693],
        [0.01662383, 0.56472807, 0.15544501, 0.4214989 ],
        [0.0595924 , 0.36552063, 0.14548442, 0.69220457],
        [0.91450184, 0.06390094, 0.92525869, 0.08833247],
        [0.16974622, 0.6435731 , 0.61417719, 0.14049905]],

       [[0.89140698, 0.22622747, 0.4281041 , 0.14201057],
        [0.97084368, 0.06373716, 0.5052015 , 0.68067798],
        [0.96921798, 0.474591  , 0.58331065, 0.56700384],
        [0.74797248, 0.08009812, 0.14261048, 0.63379681],
        [0.5359251 , 0.57885493, 0.22358957, 0.31947565]]])

In [29]:
arr = np.arange(1,11)  # it will create 1D array in a specified range 
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
arr = np.ones(5)
arr 

array([1., 1., 1., 1., 1.])

In [31]:
arr = np.ones((5,4))
arr 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
arr = np.zeros((5,4))
arr 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
arr.astype(int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
arr.dtype

dtype('float64')

In [35]:
arr = np.linspace(1,10,5)
arr 

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [36]:
arr = np.random.randint(1,12,10)
arr 

array([ 6, 11, 10,  3,  2,  4,  2,  2,  8,  3], dtype=int32)

In [37]:
np.sum(arr)

np.int64(51)

In [38]:
## aggregation function 
variance = arr.var()  # std()    #var()     #mean()    # mean ==average ,  #sum()     #max()   #min()
np.sqrt(variance)

np.float64(3.269556544854363)

In [39]:
np.power(2,3)

np.int64(8)

In [40]:
print(arr)
print(np.cumsum(arr))  # cumulative sum 

[ 6 11 10  3  2  4  2  2  8  3]
[ 6 17 27 30 32 36 38 40 48 51]


In [41]:
arr.sort()  # ascending order 

In [42]:
arr 

array([ 2,  2,  2,  3,  3,  4,  6,  8, 10, 11], dtype=int32)

In [43]:
arr[::-1]  # descending order 

array([11, 10,  8,  6,  4,  3,  3,  2,  2,  2], dtype=int32)

In [44]:
arr = np.random.randint(1,12,10)
arr 

array([ 4,  2,  2,  4,  7,  5, 10,  3,  4,  1], dtype=int32)

In [45]:
arr[2] = 60  # to update the items 

In [46]:
arr 

array([ 4,  2, 60,  4,  7,  5, 10,  3,  4,  1], dtype=int32)

In [47]:
arr[1:3] = 100

In [48]:
arr 

array([  4, 100, 100,   4,   7,   5,  10,   3,   4,   1], dtype=int32)

In [49]:
arr 

array([  4, 100, 100,   4,   7,   5,  10,   3,   4,   1], dtype=int32)

In [50]:
arr = np.array([8,7,9])
arr 

array([8, 7, 9])

In [51]:
arr.argsort()      #argmax()    #argmin()

array([1, 0, 2])

In [52]:
arr = np.random.randint(1,50,(3,5,4))
arr 

array([[[18, 28, 27, 26],
        [21, 45, 30, 40],
        [42, 17,  6, 44],
        [46, 24, 30, 18],
        [34, 35, 42,  4]],

       [[ 9, 17, 23, 39],
        [ 5, 42, 18, 45],
        [17, 44,  2, 40],
        [ 9, 41,  4, 28],
        [38, 15, 41, 30]],

       [[ 6, 16, 37, 31],
        [30, 31,  1, 29],
        [ 5, 11, 41, 35],
        [ 2, 19, 16,  3],
        [15, 31, 31, 47]]], dtype=int32)

In [53]:
arr.ravel()   # convert into 1D 

array([18, 28, 27, 26, 21, 45, 30, 40, 42, 17,  6, 44, 46, 24, 30, 18, 34,
       35, 42,  4,  9, 17, 23, 39,  5, 42, 18, 45, 17, 44,  2, 40,  9, 41,
        4, 28, 38, 15, 41, 30,  6, 16, 37, 31, 30, 31,  1, 29,  5, 11, 41,
       35,  2, 19, 16,  3, 15, 31, 31, 47], dtype=int32)

In [54]:
arr.flatten() #convert into Flat 

array([18, 28, 27, 26, 21, 45, 30, 40, 42, 17,  6, 44, 46, 24, 30, 18, 34,
       35, 42,  4,  9, 17, 23, 39,  5, 42, 18, 45, 17, 44,  2, 40,  9, 41,
        4, 28, 38, 15, 41, 30,  6, 16, 37, 31, 30, 31,  1, 29,  5, 11, 41,
       35,  2, 19, 16,  3, 15, 31, 31, 47], dtype=int32)

In [55]:
arr.reshape(60) #   3*5*4 = 60 

array([18, 28, 27, 26, 21, 45, 30, 40, 42, 17,  6, 44, 46, 24, 30, 18, 34,
       35, 42,  4,  9, 17, 23, 39,  5, 42, 18, 45, 17, 44,  2, 40,  9, 41,
        4, 28, 38, 15, 41, 30,  6, 16, 37, 31, 30, 31,  1, 29,  5, 11, 41,
       35,  2, 19, 16,  3, 15, 31, 31, 47], dtype=int32)

In [56]:
arr.size   # total no of items 

60

In [57]:
arr.reshape(10,6)

array([[18, 28, 27, 26, 21, 45],
       [30, 40, 42, 17,  6, 44],
       [46, 24, 30, 18, 34, 35],
       [42,  4,  9, 17, 23, 39],
       [ 5, 42, 18, 45, 17, 44],
       [ 2, 40,  9, 41,  4, 28],
       [38, 15, 41, 30,  6, 16],
       [37, 31, 30, 31,  1, 29],
       [ 5, 11, 41, 35,  2, 19],
       [16,  3, 15, 31, 31, 47]], dtype=int32)

In [58]:
arr.reshape(20,4)  # resize()

ValueError: cannot reshape array of size 60 into shape (20,4)

In [96]:
np.resize(arr,(20,4))   # duplicates 

array([[43, 31, 20, 43],
       [16,  6, 29, 23],
       [48, 36,  5,  5],
       [45, 48, 46, 13],
       [29, 27, 46, 17],
       [37, 25,  7, 38],
       [18, 26, 25, 16],
       [11, 12,  5, 42],
       [ 5, 11, 44, 43],
       [41, 40, 49, 41],
       [47, 25,  5, 25],
       [20, 26, 42,  1],
       [15,  1, 23, 15],
       [47, 49, 49, 47],
       [37, 29, 16, 27],
       [43, 31, 20, 43],
       [16,  6, 29, 23],
       [48, 36,  5,  5],
       [45, 48, 46, 13],
       [29, 27, 46, 17]], dtype=int32)

In [97]:
arr = np.random.randint(1,12,11)
arr 

array([ 8,  5,  2,  6,  5,  8,  4, 11,  4, 11,  1], dtype=int32)

In [101]:
arr = np.random.randint(1,50,(5,3))
arr 

array([[12, 20, 46],
       [30, 36, 12],
       [ 8,  3,  6],
       [ 2,  4, 34],
       [16, 42, 36]], dtype=int32)

In [102]:
np.transpose(arr)   # are same ==>   arr.T   

array([[12, 30,  8,  2, 16],
       [20, 36,  3,  4, 42],
       [46, 12,  6, 34, 36]], dtype=int32)

In [104]:
arr.T    # transpose 

array([[12, 30,  8,  2, 16],
       [20, 36,  3,  4, 42],
       [46, 12,  6, 34, 36]], dtype=int32)

In [106]:
## metrics operation 
arr = np.random.randint(1,50,10)
print(arr )
print(arr + 2 )

[42 10 20 27 29 14 44 36 25  4]
[44 12 22 29 31 16 46 38 27  6]


In [107]:
print(arr)
print(arr * 2)

[42 10 20 27 29 14 44 36 25  4]
[84 20 40 54 58 28 88 72 50  8]


In [114]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([5,5,5,5])
print(arr1)
print(arr2)

[10 20 30 40]
[5 5 5 5]


In [116]:
print(arr1)
print(arr2)
print(arr1 + arr2) 

[10 20 30 40]
[5 5 5 5]
[15 25 35 45]


In [3]:
arr = np.random.randint(1,200,200)
arr 

array([ 24, 101,  50,  33,  32, 158,  76, 198, 124,  99,  36, 193, 198,
       150, 114, 178, 150, 168, 142, 130,  89, 193, 155, 136, 154, 168,
       143,  14, 178,  90, 117,  92, 150,  84,  29,  92, 115, 190,  29,
       174,  72,  32, 198,  74, 156,  19,  24, 135, 196, 102,  60, 149,
         5,  46,  31, 125, 126, 104, 105,  16,  52,  23,  63,   3,  76,
       195, 194,   5,  66,  34, 161, 103,  36,  41,  74,  32,  83, 109,
        11, 120, 125, 133, 181, 122, 184,  61,  18, 122, 196, 134, 182,
        88,  18, 193, 148, 131, 189, 149, 150,  83,  82,  95,  35,  38,
        45,  34,  19, 139, 131,  89,  37,  56, 123, 150, 141, 119,  62,
        61, 168, 121, 110, 123, 137, 167,  87,  46,  82, 146, 175,  96,
       196, 165,  47,  23,   1,  43, 178, 143, 106, 117, 125, 141, 185,
        31,  48,  55,  78, 151,  40, 119, 154, 165,  30,  51,  21,  42,
        26, 163,  79, 148, 184, 103, 143, 151, 173,  64,  66, 190,  54,
        20, 188, 187,  49, 185, 180,  60, 115,  42,  66, 125, 18

In [6]:
temp = []
for item in arr:
    if item < 100 :
        temp.append(int(item))
print(temp)
print(len(temp))    

[24, 50, 33, 32, 76, 99, 36, 89, 14, 90, 92, 84, 29, 92, 29, 72, 32, 74, 19, 24, 60, 5, 46, 31, 16, 52, 23, 63, 3, 76, 5, 66, 34, 36, 41, 74, 32, 83, 11, 61, 18, 88, 18, 83, 82, 95, 35, 38, 45, 34, 19, 89, 37, 56, 62, 61, 87, 46, 82, 96, 47, 23, 1, 43, 31, 48, 55, 78, 40, 30, 51, 21, 42, 26, 79, 64, 66, 54, 20, 49, 60, 42, 66, 24, 29, 24, 43, 59, 87]
89


In [10]:
arr[arr > 100]    # try with multiple 

array([101, 158, 198, 124, 193, 198, 150, 114, 178, 150, 168, 142, 130,
       193, 155, 136, 154, 168, 143, 178, 117, 150, 115, 190, 174, 198,
       156, 135, 196, 102, 149, 125, 126, 104, 105, 195, 194, 161, 103,
       109, 120, 125, 133, 181, 122, 184, 122, 196, 134, 182, 193, 148,
       131, 189, 149, 150, 139, 131, 123, 150, 141, 119, 168, 121, 110,
       123, 137, 167, 146, 175, 196, 165, 178, 143, 106, 117, 125, 141,
       185, 151, 119, 154, 165, 163, 148, 184, 103, 143, 151, 173, 190,
       188, 187, 185, 180, 115, 125, 189, 110, 182, 181, 158, 192, 112,
       184, 147, 101, 110, 145, 143, 176], dtype=int32)

In [14]:
arr = np.random.randint(1,40,20)
np.where(arr<10)  # data  filter 

(array([ 2, 10, 11, 15]),)

In [15]:
arr 

array([29, 19,  4, 31, 23, 25, 36, 37, 33, 34,  1,  4, 38, 26, 27,  2, 18,
       17, 20, 38], dtype=int32)

In [16]:
arr1 = np.random.randint(1,20,5)
arr2 = np.random.randint(1,20,5)
print(arr1)
print(arr2)

[ 2 10 11 17 13]
[11  8 11 11 12]


In [19]:
arr3 = np.concatenate((arr1,arr2))
arr3

array([ 2, 10, 11, 17, 13, 11,  8, 11, 11, 12], dtype=int32)

In [29]:
# 2D + 2D 
arr1 = np.random.randint(1,20,(5,4))
arr2 = np.random.randint(1,20,(5,1))
print(arr1)
print()
print(arr2)

[[13 11  2  9]
 [19  7 13 16]
 [14  1 17  7]
 [ 9 11  7 11]
 [19 13  6  1]]

[[ 9]
 [15]
 [ 9]
 [14]
 [17]]


In [30]:
np.concatenate((arr1,arr2),axis=1)

array([[13, 11,  2,  9,  9],
       [19,  7, 13, 16, 15],
       [14,  1, 17,  7,  9],
       [ 9, 11,  7, 11, 14],
       [19, 13,  6,  1, 17]], dtype=int32)

In [35]:
arr1 = np.random.randint(1,20,(5,4))
arr2 = np.random.randint(1,20,(4,1))
print(arr1)
print()
print(arr2)

[[16  6  9  4]
 [11 14 16 15]
 [11 10  8  9]
 [ 8 14 11  1]
 [ 1 15  8 12]]

[[ 5]
 [11]
 [11]
 [18]]


In [38]:
np.concatenate((arr1,arr2.T),axis=0)

array([[16,  6,  9,  4],
       [11, 14, 16, 15],
       [11, 10,  8,  9],
       [ 8, 14, 11,  1],
       [ 1, 15,  8, 12],
       [ 5, 11, 11, 18]], dtype=int32)

In [39]:
# 2D + 1D 
arr1 = np.random.randint(1,20,(5,4))
arr2 = np.random.randint(1,20,4)
print(arr1)
print()
print(arr2)

[[17 11  3 19]
 [10 13 16  5]
 [ 8  9 17  9]
 [ 1  5  3 19]
 [10 17  5 19]]

[ 4 10 13 11]


In [40]:
arr1.shape , arr2.shape 

((5, 4), (4,))

In [43]:
np.vstack((arr1,arr2))


array([[17, 11,  3, 19],
       [10, 13, 16,  5],
       [ 8,  9, 17,  9],
       [ 1,  5,  3, 19],
       [10, 17,  5, 19],
       [ 4, 10, 13, 11]], dtype=int32)

In [59]:
np.vsplit()
np.hsplit() 

TypeError: vsplit() missing 2 required positional arguments: 'ary' and 'indices_or_sections'